frontend:
  - changed-files:
      - any-glob-to-any-file: 'apps/web/**'

backend:
  - changed-files:
      - any-glob-to-any-file: 'apps/api/**'

packages:
  - changed-files:
      - any-glob-to-any-file: 'packages/**'

documentation:
  - changed-files:
      - any-glob-to-any-file: '**/*.md'

ci:
  - changed-files:
      - any-glob-to-any-file: '.github/**'
