services:
  - type: web
    name: payflow-api
    env: docker
    dockerfilePath: ./docker/api.Dockerfile
    dockerContext: .
    region: ohio
    plan: free
    numInstances: 1
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 3333
      - key: FRONTEND_URL
        value: https://payflow-platform.vercel.app
    autoDeploy: true
